import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo.png" width="500" height="500"/>
        <h1 className={styles.title}>
          Welcome to <span className={styles.yellow}>PRO</span><span className={styles.grey}>RUM</span>
        </h1>
          <h4 className="text-secondary">
              Discussion Forum for Programmer
          </h4>
      </main>
    </div>
  )
}

export default Home
